### ISSUE TITLE
pipenv install

### ISSUE THREAD

**Issue by vaclavkanera** [philippnormann/chia-monitor#69]
Fresh Ubuntu 22.04 installation
Grafana installed and running on localhost:3000
Prometheus installed and running on localhost:9090
Python 3.10.4 installed

After "pipenv install" command I have this error:
chiaminer@grapheneTest:~$ cd chia-monitor/
chiaminer@grapheneTest:~/chia-monitor$ pipenv install
Traceback (most recent call last):
  File "/usr/bin/pipenv", line 33, in <module>
    sys.exit(load_entry_point('pipenv==11.9.0', 'console_scripts', 'pipenv')())
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pipenv/cli.py", line 347, in install
    from .import core
  File "/usr/lib/python3/dist-packages/pipenv/core.py", line 21, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/pipenv/vendor/requests/__init__.py", line 65, in <module>
    from . import utils
  File "/usr/lib/python3/dist-packages/pipenv/vendor/requests/utils.py", line 27, in <module>
    from .cookies import RequestsCookieJar, cookiejar_from_dict
  File "/usr/lib/python3/dist-packages/pipenv/vendor/requests/cookies.py", line 172, in <module>
    class RequestsCookieJar(cookielib.CookieJar, collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
chiaminer@grapheneTest:~/chia-monitor$

Any solutions?

**Comment by stefan-lange** [comment]
There seem to be some incompatibilities with Python 3.10. I had similar issues and in the end I used 3.9 in my chia images. I'll hope Philipp has some time in the near future to make adjustments.

**Comment by nothingshocking** [comment]
Looks like part of the problem at least..

In python 10 the module MutableMapping has moved from:
collections.MutableMapping
to
collections.abc.MutableMapping

https://github.com/pymedusa/Medusa/issues/10253#issuecomment-1015871418

**Comment by scrutinously** [comment]
I know this is old, but I managed to get it working with python 3.10 installed on my system by first deleting the chia-monitor virtualenv at .local/shar/virtualenvs/, re-running pipenv install (with errors that some dependencies didn't install) and then haphazardly updating the virtualenv after . 

To upgrade the env: first source the virtual environment's activate command (for me it was `source ~/.local/share/virtualenvs/chia-monitor-C_4nEwXv/bin/activate` (should say `(chia-monitor)` on your command line) then upgrade pip inside the virtual env with `python -m pip install --upgrade pip`. Then you need to manually install with pip: blspy, chiapos, and chiavdf with `pip install` for each one.  Mine worked after that.

**Comment by xporterfield** [comment]
After messing around with this for the last hour, I got it working in Ubuntu 22.04 with `pipenv lock --clear`

I think.
